django_core/django_core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('report/', include('report.urls', namespace='report')),  # Including the report app's URLs
    path('', include('django_module_basic.urls')),
]

django_core/django_module_basic/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import  (
    ModelListView, ModelDetailView,ModelCreateView,ModelUpdateView,ModelDeleteView,
    AreaCreateView,AreaUpdateView,AreaDetailView,AreaDeleteView,AreaListView,
    ClassUpdateView,ClassListView, ClassDetailView,ClassCreateView,ClassDeleteView,
    GroupListView,GroupDetailView,GroupCreateView,GroupUpdateView,GroupDeleteView,
    UsersPerAreaView,
    RecordListView,
)

app_name = 'django_module_basic'

urlpatterns = [
    path('', ModelListView.as_view(), name='model-list'),  # List all models
    path('category/<slug:category_slug>/', ModelListView.as_view(), name='model-list-by-category'),  # Filter models by category
    path('<int:pk>/', ModelDetailView.as_view(), name='detail'),  # Detail view of a specific model
    path('create/', ModelCreateView.as_view(), name='model-create'),
    path('<int:pk>/update/', ModelUpdateView.as_view(), name='model-update'),
    path('<int:pk>/delete/', ModelDeleteView.as_view(), name='model-delete'),
    #Area Urls 
    path('areas/', AreaListView.as_view(), name='area-list'),
    path('area/<int:pk>/', AreaDetailView.as_view(), name='area-detail'),
    path('area/create/', AreaCreateView.as_view(), name='area-create'),
    path('area/update/<int:pk>/', AreaUpdateView.as_view(), name='area-update'),
    path('area/delete/<int:pk>/', AreaDeleteView.as_view(), name='area-delete'),
    #Class urls
    path('classes/', ClassListView.as_view(), name='class-list'),
    path('class/<int:pk>/', ClassDetailView.as_view(), name='class-detail'),
    path('class/create/', ClassCreateView.as_view(), name='class-create'),
    path('class/update/<int:pk>/', ClassUpdateView.as_view(), name='class-update'),
    path('class/delete/<int:pk>/', ClassDeleteView.as_view(), name='class-delete'),
    #Group urls  
    path('groups/', GroupListView.as_view(), name='group-list'),
    path('groups/<int:pk>/', GroupDetailView.as_view(), name='group-detail'),
    path('groups/create/', GroupCreateView.as_view(), name='group-create'),
    path('groups/<int:pk>/update/', GroupUpdateView.as_view(), name='group-update'),
    path('groups/<int:pk>/delete/', GroupDeleteView.as_view(), name='group-delete'),
    #Report urls
    path('area/<int:pk>/users/', UsersPerAreaView.as_view(), name='users_per_area'),
    #Login views 
    path('login/', auth_views.LoginView.as_view(template_name='django_module_basic/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #Registred view
    path('records/', RecordListView.as_view(), name='records'),
]

django_core/report/urls.py
# report/urls.py
from django.urls import path
from .views import check_in,check_out
app_name= 'report'
urlpatterns = [
    path('check-in/', check_in, name='check-in'),
    path('check-out/', check_out, name='check-out'),
    # Add other paths here
]

django_core/django_module_basic/models.py
from django.db import models
from django.utils.text import slugify
from .code_generator import generate_code
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ['title']
    def __str__(self):
        return self.title





# New models

class Area(models.Model):
    area_of_use = models.CharField(max_length=200)
    users = models.ManyToManyField(User, related_name='areas', blank=True)

    @property
    def user_count(self):
        return self.users.count()  # Count the number of related users

    def __str__(self):
        return self.area_of_use

class Class(models.Model):
    class_name = models.CharField(max_length=200)

    def __str__(self):
        return self.class_name

class Group(models.Model):
    group_name = models.CharField(max_length=200)

    def __str__(self):
        return self.group_name
    

class ModelTest(models.Model):
    autor = models.ForeignKey(User, 
        on_delete=models.CASCADE, 
        null=True, blank=True)
    category = models.ForeignKey(Category,
        related_name='models',
        on_delete=models.CASCADE)
    group = models.ForeignKey(Group, 
        related_name='models', 
        on_delete=models.CASCADE, 
        null=True, blank=True)
    class_model = models.ForeignKey(Class, 
        related_name='modeltests', 
        on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=10, unique=True, blank=True) # Allow it to be blank
    #Atributtes of the registred of time
    arrival_time = models.DateTimeField(blank=True, null=True)
    departure_time = models.DateTimeField(blank=True, null=True)


    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.code: # Generate code only if it's not already set
            self.code = generate_code()

        if not self.slug:
            self.slug = slugify(self.code)

        super(ModelTest, self).save(*args, **kwargs)
        
class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    class_model = models.ForeignKey(Class, on_delete=models.CASCADE)
    code = models.CharField(max_length=10)
    arrival_time = models.DateTimeField(null=True, blank=True)
    departure_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} - {self.code}"

django_core/django_module_basic/forms.py
from django import forms
from .code_generator import generate_code
from .models import  ModelTest,Area,Class

class ModelTestAdminForm(forms.ModelForm):
    class Meta:
        model = ModelTest
        fields = '__all__'

    code = forms.CharField(
        label='Preview Code',
        widget=forms.TextInput(attrs={'readonly': 'readonly'}),
        required=False,
        initial=generate_code()
    )


class ModelTestForm(forms.ModelForm):
    class Meta:
        model = ModelTest
        fields = [ 'autor','first_name','last_name','category','group']


class AreaForm(forms.ModelForm):
    class Meta:
        model = Area
        fields = ['area_of_use']


class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ['class_name']

django_core/django_module_basic/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from .forms import ModelTestForm,AreaForm,ClassForm
from django.views.generic import ListView,DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from .models import ModelTest,Category,Area,Class,Group,Report
from .mixins import CommonContextMixin
from django.views.generic import TemplateView


# Create your views here.


#class IndexView(TemplateView):
#   template_name = 'index/index.html'


class ModelListView(CommonContextMixin,ListView):
    model = ModelTest  # Set the model to 'ModelTest'
    template_name = 'django_module_basic/model_list.html'  # Specify the template for the list view
    context_object_name = 'model_list'  # Name of the variable to use in the template
    paginate_by = 3  # Display 10 items per page
    
    
    def get_queryset(self):
        queryset = super().get_queryset()
        category_slug = self.kwargs.get('category_slug')
        if category_slug:
            queryset = queryset.filter(category__slug=category_slug)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['areas'] = Area.objects.all()
        categories = Category.objects.prefetch_related('models')
        context['categories_with_models'] = categories
        return context
    


class ModelDetailView(CommonContextMixin,DetailView):
    model = ModelTest  # Set the model to 'ModelTest'
    template_name = 'django_module_basic/model_detail.html'  # Specify the template for the detail view
    context_object_name = 'model'  # Name of the variable to use in the template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class ModelCreateView(CommonContextMixin,CreateView):
    model = ModelTest
    form_class = ModelTestForm
    template_name = 'django_module_basic/model_form.html'
    success_url = reverse_lazy('django_module_basic:model-list')


    

class ModelUpdateView(CommonContextMixin,UpdateView):
    model = ModelTest
    form_class = ModelTestForm
    template_name = 'django_module_basic/model_form.html'
    success_url = reverse_lazy('django_module_basic:model-list')



class ModelDeleteView(CommonContextMixin,DeleteView):
    model = ModelTest
    template_name = 'django_module_basic/model_confirm_delete.html'
    success_url = reverse_lazy('django_module_basic:model-list')

#Area list view
class AreaListView(CommonContextMixin, ListView):
    model = Area
    template_name = 'django_module_basic/area_list.html'
    context_object_name = 'areas'
    paginate_by = 3

class AreaDetailView(CommonContextMixin,DetailView):
    model = Area
    template_name = 'django_module_basic/area_detail.html'
    context_object_name = 'area'

class AreaCreateView(CommonContextMixin,CreateView):
    model = Area
    form_class = AreaForm
    template_name = 'django_module_basic/area_form.html'
    success_url = reverse_lazy('django_module_basic:model-list')

class AreaUpdateView(CommonContextMixin,UpdateView):
    model = Area
    form_class = AreaForm
    template_name = 'django_module_basic/area_form.html'
    success_url = reverse_lazy('django_module_basic:model-list')

class AreaDeleteView(CommonContextMixin,DeleteView):
    model = Area
    template_name = 'django_module_basic/area_confirm_delete.html'
    success_url = reverse_lazy('django_module_basic:model-list')


#Class view
class ClassListView(CommonContextMixin, ListView):
    model = Class
    template_name = 'django_module_basic/class_list.html'
    context_object_name = 'classes'
    paginate_by = 3

 

class ClassDetailView(CommonContextMixin, DetailView):
    model = Class
    template_name = 'django_module_basic/class_detail.html'
    context_object_name = 'class'

class ClassCreateView(CommonContextMixin, CreateView):
    model = Class
    form_class = ClassForm
    template_name = 'django_module_basic/class_form.html'
    success_url = reverse_lazy('django_module_basic:class-list')

class ClassUpdateView(CommonContextMixin, UpdateView):
    model = Class
    form_class = ClassForm
    template_name = 'django_module_basic/class_form.html'
    success_url = reverse_lazy('django_module_basic:class-list')

class ClassDeleteView(CommonContextMixin, DeleteView):
    model = Class
    template_name = 'django_module_basic/class_confirm_delete.html'
    success_url = reverse_lazy('django_module_basic:class-list')

#Group view
class GroupListView(CommonContextMixin,ListView):
    model = Group
    template_name = 'django_module_basic/group_list.html'
    context_object_name = 'groups'
    paginate_by = 3



class GroupDetailView(CommonContextMixin,DetailView):
    model = Group
    template_name = 'django_module_basic/group_detail.html'
    context_object_name = 'group'

class GroupCreateView(CommonContextMixin,CreateView):
    model = Group
    fields = ['group_name']
    template_name = 'django_module_basic/group_form.html'
    success_url = reverse_lazy('django_module_basic:group-list')
                                                        
class GroupUpdateView(CommonContextMixin,UpdateView):
    model = Group
    fields = ['group_name']
    template_name = 'django_module_basic/group_form.html'
    success_url = reverse_lazy('django_module_basic:group-list')

class GroupDeleteView(CommonContextMixin,DeleteView):
    model = Group
    template_name = 'django_module_basic/group_confirm_delete.html'
    success_url = reverse_lazy('django_module_basic:group-list')

#Views for the report

class UsersPerAreaView(DetailView):
    model = Area
    template_name = 'django_module_basic/users_per_area.html'
    context_object_name = 'area'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users_by_category = {}
        total_user_count = self.object.users.count()

        # Organize users by category and count them
        for user in self.object.users.all():
            model_tests = ModelTest.objects.filter(first_name=user.first_name)
            for model_test in model_tests:
                category = model_test.category.title
                if category not in users_by_category:
                    users_by_category[category] = {
                        'users': [],
                        'count': 0
                    }
                users_by_category[category]['users'].append((user, model_test.class_model))  # Include class_model here
                users_by_category[category]['count'] += 1

        context['users_by_category'] = users_by_category
        context['total_user_count'] = total_user_count
        return context

class RecordListView(ListView):
    template_name = 'django_module_basic/record_list.html'
    queryset = Report.objects.all()  # Retrieve all ModelTest instances
    context_object_name = 'records'

django_core/django_module_basic/templates/django_module_basic/area_confirm_delete.html
{% extends "django_module_basic/base.html" %}

{% block content %}
  <h2>Are you sure you want to delete "{{ area.area_of_use }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
  <a href="{% url 'django_module_basic:area-detail' area.pk %}">Cancel</a>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/area_detail.html
{% extends "django_module_basic/base.html" %}

{% block content %}
  <h2>{{ area.area_of_use }}</h2>
  <a href="{% url 'django_module_basic:area-update' area.pk %}">Edit</a> |
  <a href="{% url 'django_module_basic:area-delete' area.pk %}">Delete</a>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/area_form.html
{% extends "django_module_basic/base.html" %}

{% block content %}
  <h2>{% if form.instance.pk %}Edit Area{% else %}Create Area{% endif %}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/area_list.html
{% extends "django_module_basic/base.html" %}

{% block title %}Area List{% endblock %}

{% block content %}
  <h2>Area List</h2>
  <ul>
    <a href="{% url 'django_module_basic:area-create' %}">Create area</a>
    {% for area in areas %}
      <li><a href="{% url 'django_module_basic:area-detail' area.pk %}">{{ area.area_of_use }}</a></li>
      <a href="{% url 'django_module_basic:area-update' area.pk %}">Edit</a> |
      <a href="{% url 'django_module_basic:area-delete' area.pk %}">Delete</a>
      <a href="{% url 'django_module_basic:users_per_area' area.pk %}">User Report</a>
    {% endfor %}
  </ul>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/class_confirm_delete.html
{% extends 'django_module_basic/base.html' %}

{% block title %}Delete Class{% endblock %}

{% block content %}
  <h2>Are you sure you want to delete "{{ class.class_name }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
  <a href="{% url 'django_module_basic:class-detail' class.pk %}">Cancel</a>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/class_detail.html
{% extends 'django_module_basic/base.html' %}

{% block title %}Class Detail{% endblock %}

{% block content %}
  <h2>{{ class.class_name }}</h2>
  <a href="{% url 'django_module_basic:class-update' class.pk %}">Edit</a> |
  <a href="{% url 'django_module_basic:class-delete' class.pk %}">Delete</a>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/class_form.html
{% extends 'django_module_basic/base.html' %}

{% block title %}Create or Update Class{% endblock %}

{% block content %}
  <h2>{% if form.instance.pk %}Edit Class{% else %}Create Class{% endif %}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/class_list.html
{% extends 'django_module_basic/base.html' %}


{% block title %}Class List{% endblock %}

{% block content %}
  <h2>Classes</h2>
  <ul>
    {% for class in classes %}
      <li><a href="{% url 'django_module_basic:class-detail' class.pk %}">{{ class.class_name }}</a></li>
    {% endfor %}
  </ul>
  <a href="{% url 'django_module_basic:class-create' %}">Add New Class</a>
{% endblock %}
                                                                                                                                 

django_core/django_module_basic/templates/django_module_basic/group_confirm_delete.html
{% extends 'django_module_basic/base.html' %}

{% block title %}Delete Group{% endblock %}

{% block content %}
<h2>Are you sure you want to delete "{{ group.group_name }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
</form>
<a href="{% url 'django_module_basic:group-list' %}">Cancel</a>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/group_detail.html
{% extends 'django_module_basic/base.html' %}

{% block title %}Class Detail{% endblock %}

{% block content %}
  <h2>{{ group.group_name }}</h2>
  <a href="{% url 'django_module_basic:group-update' group.pk %}">Edit</a> |
  <a href="{% url 'django_module_basic:group-delete' group.pk %}">Delete</a>
 {% endblock %}

django_core/django_module_basic/templates/django_module_basic/group_form.html
{% extends 'django_module_basic/base.html' %}

{% block title %}Group Form{% endblock %}

{% block content %}
<h2>{{ view.title }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/model_confirm_delete.html
{% extends 'django_module_basic/base.html' %}

{% block title %}Delete Model{% endblock %}

{% block content %}
    <h2>Delete Model</h2>
    <p>Are you sure you want to delete "{{ model.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
        <a href="{% url 'django_module_basic:model-list' %}">Cancel</a>
    </form>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/model_detail.html
{% extends 'django_module_basic/base.html' %}

{% block title %}{{ model.title }}{% endblock %}

{% block content %}
    <p>First name:{{ model.first_name }}</p>
    <p>Last name:{{ model.last_name }}</p>
    <p>Category: {{ model.category.title }}</p>
    <p>Created: {{ model.created }}</p>
    <p>Code: {{ model.code }}</p>
{% endblock %}

django_core/django_module_basic/templates/django_module_basic/users_per_area.html
{% extends 'django_module_basic/base.html' %}
{% block title %}Users in area {{ area.area_of_use }}{% endblock %}
{% block content %}
<h1>Users in {{ area.area_of_use }}</h1>
<h2>Total Users: {{ total_user_count }}</h2>
{% for category, data in users_by_category.items %}
  <h2>Category: {{ category }} ({{ data.count }} users)</h2>
  <ul>
    {% for user, class_model in data.users %}
      <li>{{ user.first_name }} {{ user.last_name }} - {{ class_model }}</li>
    {% endfor %}
  </ul>
{% endfor %}
<a href="{% url 'django_module_basic:area-list' %}">Back to Areas</a>
{% endblock %}
                                                                 